# Generated by Django 4.0.1 on 2022-03-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='ststus',
            new_name='status',
        ),
    ]
