# Generated by Django 4.0.1 on 2022-03-17 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_catagory_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='zipcode',
        ),
    ]
