# Generated by Django 4.0.1 on 2022-03-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_customer_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='locality',
        ),
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.CharField(default=333, max_length=10),
            preserve_default=False,
        ),
    ]
