# Generated by Django 4.0.1 on 2022-04-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_request_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='title',
        ),
        migrations.AddField(
            model_name='request',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='quantity',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
