# Generated by Django 4.0.1 on 2022-04-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_request_title_request_name_request_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
